namespace: monitoring
resources:
- manifests/alertmanager.yaml
# this for metrics
- manifests/kubeMetrics/cluster-role-binding.yaml
- manifests/kubeMetrics/cluster-role.yaml
- manifests/kubeMetrics/deployment.yaml
- manifests/kubeMetrics/service-account.yaml
- manifests/kubeMetrics/service.yaml

generatorOptions:
  disableNameSuffixHash: true
